nodeLinker: node-modules


# Set the base branch for `yarn version check` command
# While we're not using `yarn version` workflow yet, this is still useful
# for developers to know which packages need to be updated
changesetBaseRefs: ["develop", "origin/develop"]

# Disable yarn metrics
enableTelemetry: false